# shell-runner configuration

# prepare gitlab-ci
before_script:
- apt-get update -y -q;
- apt-get upgrade -y -q;
- apt-get install git unzip libicu-dev libz-dev libbz2-dev -y;
- docker-php-ext-install intl;
- docker-php-ext-install zip;
- docker-php-ext-install gettext;
- curl -sS https://getcomposer.org/installer | php
- php composer.phar --version
- curl -o phpunit https://phar.phpunit.de/phpunit-5.5.0.phar
- chmod +x phpunit
- ./phpunit --version
- php -m
- php -d memory_limit=-1 composer.phar install

# include services
# define types/stages
types:
- test
- build
- deploy
- cleanup

# define jobs

# testing with php 5.x jobs
test-php5_job:
  type: test
  image: php:5.6
  script:
  - php -d memory_limit=-1 vendor/bin/phpunit --colors --debug --configuration ./tests/phpunit.xml --coverage-text
  allow_failure: false

# testing with php 7.x jobs
test-php7_job:
  type: test
  image: php:7.0
  script:
  - php -d memory_limit=-1 vendor/bin/phpunit --colors --debug --configuration ./tests/phpunit.xml --coverage-text
  allow_failure: false

build_job:
  type: build
  image: php:5.6
  script:
  - php -d memory_limit=-1 vendor/bin/phpunit --colors --debug --configuration ./tests/phpunit.xml --coverage-text
  allow_failure: false

trigger:
  type: deploy
  image: php:5.6
  script:
  - php -d memory_limit=-1 vendor/bin/phpunit --colors --debug --configuration ./tests/phpunit.xml --coverage-text
